name: PROD Deployment updated

on:
  push:
    branches: [main]

jobs:
  Maintenance:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: /home/ubuntu/git/sample-node-project
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Install dependencies and start
        working-directory: /home/ubuntu/git/sample-node-project
        run: |
          npm install
          npm start
