name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  Maintenance :
      runs-on: [self-hosted, linux, x64, prod]
      steps:
      - uses: actions/checkout@v2
      - name: git clone
        working-directory: /home/ubuntu/git
        run: |
          gh repo clone tariqajies-svg/sample-nodejs
          cd sample-node-project
          npm install
          npm start 
