name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  Maintenance :
      runs-on: [self-hosted, linux, x64]
      steps:
      - uses: actions/checkout@v2
      - name: git clone
        working-directory: /home/ubuntu/git
        run: |
          git clone git@github.com:tariqajies-svg/sample-nodejs.git
          cd sample-nodejs
          npm install
          npm start --no-interactive & 
