name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  Maintenance :
      runs-on: [self-hosted, linux, x64, Live]
      steps:
      - uses: actions/checkout@v2
      - name: git clone
        working-directory: /home/ubuntu/git
        run: |
          git clone git@github.com:acemilyalcin/sample-node-project.git
          cd sample-node-project
          npm install
          npm start 
